version: '3.8'

services:
  money-front:
    image: paulvtbt/money-front:v1
    build:
      context: web
      dockerfile: ../docker/prod/web/Dockerfile
    hostname: front-money
    tty: true
    depends_on:
      - money-back
    ports:
      - 5173:5173
    stdin_open: true
    networks:
      - net
    
  money-back:
    image: paulvtbt/money-back:v1
    depends_on:
      - maria
    build:
      context: internal
      dockerfile: ../docker/prod/app/Dockerfile
    hostname: back-money
    networks:
      - net
    ports:
      - 80:8080
    environment:
      - MODE=prod
      - DB_USER=admin_money
      - DB_PASSWORD=sixmillekangourous
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=money
    deploy:
      restart_policy:
        condition: on-failure
      
  maria:
    image: mariadb:latest
    hostname: db
    networks:
      - net
    volumes:
      - maria-volume:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=polo
      - MARIADB_DATABASE=money
      - MARIADB_USER=admin_money
      - MARIADB_PASSWORD=sixmillekangourous
    deploy:
      placement:
        constraints:
          - node.labels.storage == maria

volumes:
  maria-volume:

networks:
  net:
    driver: overlay