version: '3.8'

services:
  money-front:
    build:
      context: web
    hostname: front_money
    container_name: front_money
    tty: true
    depends_on:
      - money-back
    ports:
      - 5173:5173
    stdin_open: true
    networks:
      - net
    
  money-back:
    depends_on:
      - maria
    build:
      context: internal
    container_name: back_money
    hostname: back_money
    networks:
      - net
    ports:
      - 80:8080
    environment:
      - DB_USER=admin_money
      - DB_PASSWORD=sixmillekangourous
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=money
    deploy:
      restart_policy:
        condition: on-failure
      
  maria:
    image: mariadb:latest
    container_name: maria-container
    hostname: db
    networks:
      - net
    volumes:
      - maria-volume:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=polo
      - MARIADB_DATABASE=money
      - MARIADB_USER=admin_money
      - MARIADB_PASSWORD=sixmillekangourous

volumes:
  maria-volume:

networks:
  net:
    driver: overlay