version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.8
    command: --providers.docker.swarmMode
    ports:
      - "80:80"
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
         - node.labels.entry == traefik
      labels:
        - traefik.enable=true
        - traefik.http.services.reverse-proxy.loadbalancer.server.port=8088

  money-front:
    image: paulvtbt/money-front:v1
    build:
      context: web
      dockerfile: ../docker/prod/web/Dockerfile
    hostname: front-money
    tty: true
    depends_on:
      - money-back
    stdin_open: true
    networks:
      - net
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.money-front.rule=Host(`paulvalentintalbot.com`)
        - traefik.http.services.money-front.loadbalancer.server.port=80
    
  money-back:
    image: paulvtbt/money-back:v1
    depends_on:
      - maria
      - redis
    build:
      context: internal
      dockerfile: ../docker/prod/app/Dockerfile
    hostname: back-money
    networks:
      - net
    environment:
      - GIN_MODE=release
      - PORT=8080
      - DB_USER=admin_money
      - DB_PASSWORD=sixmillekangourous
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=money
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.services.money-back.loadbalancer.server.port=8080
        - traefik.http.routers.money-back.rule=Host(`api.paulvalentintalbot.com`)
      
  maria:
    image: mariadb:latest
    hostname: db
    networks:
      - net
    volumes:
      - maria-volume:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=polo
      - MARIADB_DATABASE=money
      - MARIADB_USER=admin_money
      - MARIADB_PASSWORD=sixmillekangourous
    labels:
      - traefik.enable=false
    deploy:
      placement:
        constraints:
          - node.labels.storage == maria
      labels:
        - traefik.enable=false
        - traefik.http.services.maria.loadbalancer.server.port=3306

  redis:
    image: redis:7-alpine
    hostname: redis-db
    command: redis-server --requirepass deuxmillekangourous --save 60 1
    networks:
      - net
    volumes:
      - redis-volume:/data
    labels:
      - traefik.enable=false
    deploy:
      placement:
        constraints:
          - node.labels.storagekeyvalue == redis
      labels:
        - traefik.enable=false
        - traefik.http.services.redis.loadbalancer.port=6379

volumes:
  maria-volume:
  redis-volume:

networks:
  net:
    driver: overlay