// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateExpenseInput struct {
	Amount int       `json:"amount"`
	Date   time.Time `json:"date"`
}

type CreateUserInput struct {
	Name      string `json:"name"`
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type DeleteExpenseInput struct {
	ID string `json:"id"`
}

type Expense struct {
	ID     string    `json:"id"`
	Amount int       `json:"amount"`
	Date   time.Time `json:"date"`
}

type ExpenseSum struct {
	Amount    int       `json:"amount"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type GetExpensesInput struct {
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type GetExpensesSumInput struct {
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UpdateExpenseInput struct {
	ID     string     `json:"id"`
	Amount *int       `json:"amount"`
	Date   *time.Time `json:"date"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}
