CREATE TABLE IF NOT EXISTS revenues (
  id INT NOT NULL UNIQUE AUTO_INCREMENT,
  amount INT NOT NULL,
  date DATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP),
  user_id INT NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT `fk_revenue_user`
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
)